use invests;
CREATE TABLE IF NOT EXISTS STOCK(
	STOCK_ID INT AUTO_INCREMENT PRIMARY KEY,
    STOCK_BUY BOOLEAN NOT NULL,
    STOCK_KIND VARCHAR (255) NOT NULL,
    STOCK_DATE DATE NOT NULL,
    STOCK_COST DOUBLE NOT NULL,
	STOCK_AMOUNT DOUBLE NOT NULL,
    STOCK_INFO VARCHAR (255) NOT NULL,
    STOCK_BONUS VARCHAR (255) NOT NULL,
    STOCK_COMM TEXT,
    STOCK_ENTER_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)ENGINE INNODB
 